### ISSUE TITLE
Bitte um Hilfe...

### ISSUE THREAD

**Issue by Tiese** [GerLech/AsyncWebConfig#1]
Wie kann ich z. B. einen String in die Datei: AsyncWebConfig.cpp einfügen?
Ich habe versucht zwischen Zeile 66/67 eine Variable einzufügen, doch leider klappt es nicht so recht ;-(

```
66  "<body>\n" + INHALT +
67  "<div id='main_div' style='margin-left:15px;margin-right:15px;'>\n"
```
Funktioniert nicht :.-(

```
66  "<body>\n {INHALT} \n" 
67  "<div id='main_div' style='margin-left:15px;margin-right:15px;'>\n"
```
Geht auch nicht :-((

Vielen lieben Dank für eine kleine Hilfestellung!

**Comment by GerLech** [comment]
HTML_START ist eine String-Konstante (alle Zeilen bis zum Semikolon also die Zeilen 32 bis 69), die in Zeile 306 mit variablen Inhalten gefüllt wird. um eine weitere Variable einzufügen, muss an der entsprechenden Stelle %s für Strings oder %i für Zahlen eingefügt werden. 
z.B. "<body>\n %s \n>
In Zeile 306 muss dann der gewünschte Inhalt eingefügt werden.
    sprintf(_buf,HTML_START,**_ihre Variable als C-String_**,_apName.c_str());
Achtung! Ihre Variable muss vor _apName eingefügt werden, da das %s für den Namen ziemlich am Ender von HTML_START steht.

**Comment by Tiese** [comment]
Vielen Dank!
Es hat funktioniert :-) 👍
